version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "8000:80"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/todo_app

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
